# Kanagawa Dragon Alacritty Colors
[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.normal]
black   = "#0d0c0c"
blue    = "#8ba4b0"
cyan    = "#8ea4a2"
green   = "#8a9a7b"
magenta = "#a292a3"
red     = "#c4746e"
white   = "#C8C093"
yellow  = "#c4b28a"

[colors.bright]
black   = "#a6a69c"
blue    = "#7FB4CA"
cyan    = "#7AA89F"
green   = "#87a987"
magenta = "#938AA9"
red     = "#E46876"
white   = "#c5c9c5"
yellow  = "#E6C384"

[colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[[colors.indexed_colors]]
color = "#b6927b"
index = 16

[[colors.indexed_colors]]
color = "#b98d7b"
index = 17
